#!/usr/bin/env python3
"""Build per-column accuracy report from extracted.json (R4-2).

Inputs:
  data/extracts/00-national-yearbook-table/extracted.json (locked, 682 obs,
  deterministic, generated by extract_00_national_yearbook_table.py)

Output:
  data/extracts/00-national-yearbook-table/per_column_accuracy.json
    header        — mirrors extracted.json metadata; hash/version drift ⇒ 不一致
    per_column    — 22 列, 每列 {sample_count, coverage_pct, matched_count,
                                accuracy_pct, threshold_pct, verdict}
    summary       — 总体统计 + overall_verdict

Verdict 规则（per R4-2）：
  needs_review_pct > 50%   → overall BLOCKED (docs/08b 回滚线)
  任一列 accuracy_pct == None 或 0% 或 < threshold → overall BLOCKED
  否则 → overall PASS

确定性 (R4-1/B-07)：不读取 wall-clock；同一份 extracted.json 输入
应产出字节一致的 per_column_accuracy.json。
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
REPO = HERE.parent.parent
EXTRACTED = REPO / "data" / "extracts" / "00-national-yearbook-table" / "extracted.json"
REPORT = EXTRACTED.parent / "per_column_accuracy.json"

# docs/08b: needs_review > 50% 触发质量回滚
NEEDS_REVIEW_BLOCKED_PCT = 50.0
# 期望观测数；任何偏离此值都判定为陈旧
EXPECTED_N_OBSERVATIONS = 682
EXPECTED_N_COLUMNS = 22


def sha256_of(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _column_threshold_pct(threshold: float) -> float:
    """PER_COLUMN_MIN_ACCURACY 中阈值为 0..1 比例，转化为百分比。"""
    return round(threshold * 100.0, 1)


def build_report(extracted: dict, column_reference: dict,
                 ocr_tolerance: dict, per_column_min_accuracy: dict) -> dict:
    """根据 extracted.json 计算 per-column 准确率 + 总体 verdict。"""
    md = extracted["metadata"]
    obs = extracted["observations"]
    by_col: dict[str, list[dict]] = {}
    for o in obs:
        by_col.setdefault(o["column_key"], []).append(o)

    n_obs = len(obs)
    needs_review_total = sum(1 for o in obs if o.get("needs_review"))

    per_column: dict[str, dict] = {}
    columns_below_threshold: list[str] = []
    columns_at_zero: list[str] = []
    sum_pct = 0.0
    n_pct_cols = 0
    total_matched = 0
    total_truth = 0

    for col_key in sorted(by_col.keys()):
        truth_map = column_reference.get(col_key, {})
        tol = ocr_tolerance.get(col_key, 5.0)
        threshold = per_column_min_accuracy.get(col_key, 1.0)
        matched = 0
        for o in by_col[col_key]:
            expected = truth_map.get(o["geo_canonical"])
            if expected is None or o["value"] is None:
                continue
            if abs(o["value"] - expected) <= tol:
                matched += 1
        n_truth = len(truth_map)
        coverage_pct = round(100.0 * n_truth / 31.0, 1) if n_truth else 0.0
        accuracy_pct = (
            round(100.0 * matched / n_truth, 1) if n_truth else None
        )
        threshold_pct = _column_threshold_pct(threshold)

        if accuracy_pct is None:
            verdict = "BLOCKED"
            columns_at_zero.append(col_key)
        elif accuracy_pct == 0.0:
            verdict = "FAIL"
            columns_at_zero.append(col_key)
        elif accuracy_pct < threshold_pct:
            verdict = "FAIL"
            columns_below_threshold.append(col_key)
        else:
            verdict = "PASS"

        per_column[col_key] = {
            "sample_count": n_truth,
            "coverage_pct": coverage_pct,
            "matched_count": matched,
            "accuracy_pct": accuracy_pct,
            "threshold_pct": threshold_pct,
            "verdict": verdict,
        }
        if accuracy_pct is not None:
            sum_pct += accuracy_pct
            n_pct_cols += 1
        total_matched += matched
        total_truth += n_truth

    needs_review_pct = (
        round(100.0 * needs_review_total / n_obs, 2) if n_obs else 0.0
    )
    overall_accuracy_pct = (
        round(sum_pct / n_pct_cols, 2) if n_pct_cols else None
    )

    # Verdict 聚合
    blocking_reasons: list[str] = []
    if needs_review_pct > NEEDS_REVIEW_BLOCKED_PCT:
        blocking_reasons.append(
            f"needs_review_pct={needs_review_pct} > {NEEDS_REVIEW_BLOCKED_PCT}% (docs/08b 回滚线)"
        )
    if columns_at_zero:
        blocking_reasons.append(
            f"{len(columns_at_zero)} 个列 0%/空: {columns_at_zero[:5]}..."
        )
    if columns_below_threshold:
        blocking_reasons.append(
            f"{len(columns_below_threshold)} 个列低于门槛: "
            f"{columns_below_threshold[:5]}..."
        )

    overall_verdict = "BLOCKED" if blocking_reasons else "PASS"

    header = {
        "extractor": md["extractor"],
        "input_file": "data/extracts/00-national-yearbook-table/extracted.json",
        "input_hash_sha256": md["file_hash_sha256"],
        "input_size_bytes": md["file_size_bytes"],
        "n_observations": n_obs,
        "n_columns": len(by_col),
        "expected_n_observations": EXPECTED_N_OBSERVATIONS,
        "expected_n_columns": EXPECTED_N_COLUMNS,
        "stale_check": "header.input_hash_sha256/n_observations/n_columns "
                       "必须与 extracted.json 完全一致；不一致 ⇒ per_column_accuracy.json 已陈旧",
    }

    summary = {
        "total_matched": total_matched,
        "total_truth_samples": total_truth,
        "overall_accuracy_pct": overall_accuracy_pct,
        "needs_review_total": needs_review_total,
        "needs_review_pct": needs_review_pct,
        "needs_review_blocked_pct": NEEDS_REVIEW_BLOCKED_PCT,
        "columns_below_threshold_count": len(columns_below_threshold),
        "columns_at_zero_count": len(columns_at_zero),
        "blocking_reasons": blocking_reasons,
        "overall_verdict": overall_verdict,
    }

    return {
        "header": header,
        "per_column": per_column,
        "summary": summary,
    }


def main(argv: list[str]) -> int:
    import argparse
    sys.path.insert(0, str(HERE))
    from extract_00_national_yearbook_table import (
        COLUMN_REFERENCE, OCR_TOLERANCE, PER_COLUMN_MIN_ACCURACY,
    )
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=EXTRACTED)
    parser.add_argument("--output", type=Path, default=REPORT)
    args = parser.parse_args(argv[1:])
    if not args.input.exists():
        print(f"ERROR: {args.input} 不存在", file=sys.stderr)
        return 2
    extracted = json.loads(args.input.read_text(encoding="utf-8"))
    report = build_report(
        extracted, COLUMN_REFERENCE, OCR_TOLERANCE, PER_COLUMN_MIN_ACCURACY,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"OK: 写入 {args.output}")
    s = report["summary"]
    print(f"  overall_verdict: {s['overall_verdict']}")
    print(f"  needs_review:    {s['needs_review_total']} ({s['needs_review_pct']}%)")
    print(f"  overall_acc:     {s['overall_accuracy_pct']}%")
    print(f"  columns_at_zero: {s['columns_at_zero_count']}")
    print(f"  columns_below:   {s['columns_below_threshold_count']}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))